# yaml-language-server: $schema=../schema/virtual_device_profile_v1.json
# Schema version number
version: 1

# The type of configuration schema
kind: VirtualDeviceProfile

# Name of the device profile
name: Default

# Type of gamepad to emulate.
# "auto" will copy the name/vendor from the source devices
# Options: ["auto", "xb360", "ps3", "ps4", "ps5", "switchpro"]
gamepad_type: "xb360"

# Profile mappings
mapping:
  - name: Guide Button
    output_behavior: sequence
    source_event:
      type: EV_KEY
      code: BTN_MODE
      kind: evdev
    output_events:
      - type: EV_KEY
        code: BTN_MODE
        kind: evdev

  - name: Quick Menu Button
    output_behavior: sequence
    source_event:
      type: EV_KEY
      code: BTN_BASE
      kind: evdev
    output_events:
      - code: open_quick_menu
        kind: dbus

  - name: Keyboard Button
    output_behavior: sequence
    source_event:
      type: EV_KEY
      code: KEY_KEYBOARD
      kind: evdev
    output_events:
      - code: open_keyboard
        kind: dbus
